### ISSUE TITLE
RN 0.13 support

### ISSUE THREAD

**Issue by JonnyBGod** [FaridSafi/react-native-google-places-autocomplete#4]
This was working fine with RN 0.12 in both iOS and Android.

Now, after upgrading to RN 0.13, when selecting an item it is not closing the list and showing the selected item on the textView. When selecting again the list closes but textView is still empty.

**Comment by FaridSafi** [comment]
Thank you for reporting this issue. I will investigate in the next days.

**Comment by FaridSafi** [comment]
Hello, I published a fix. Can you confirm if it's ok for you?

**Comment by JonnyBGod** [comment]
Not fixed sorry. It just introduced a new bug.

Now when you try to tap on a list item it just closes the list without ever hitting the item. (no _inPress() hit)

I am trying to go over your code to understand the problem.
Apparently, after reverting back to the previous version, the problem lies in the fact that when focused on the textView and trying to tap on an item, you cannot hit the item (thats why it works on second tap). After  blur from textView you can tap properly but for some reason the list closes but the text is not changed on the textView.

**Comment by JonnyBGod** [comment]
I just realised I was creating a new component on every render call.

So, now that solved the problem of getting the result displayed on the textView.

However, the problem related to the need of a second tap still persists.

**Comment by FaridSafi** [comment]
The line keyboardShouldPersistTaps={true} should have fixed the second tap issue.
Are you using RN 13.2 and node > 4.2.0 ?

**Comment by JonnyBGod** [comment]
Yes.
RN 0.13.2
Node 4.2.1

Tested both on simulator and iphone 5 with ios 9.

**Comment by FaridSafi** [comment]
I just tested with a fresh install of RN and I couldn't reproduce the second tap issue. Can you please provide an example?

**Comment by JonnyBGod** [comment]
Are you testing with `onBlur={options._onBlur}` or `onBlur={this._onBlur}`?

Because if your using the later version it just closes the list on tap but does not trigger _onPress().

**Comment by FaridSafi** [comment]
with the last version which is onBlur={this._onBlur}

**Comment by JonnyBGod** [comment]
That version does not work at all as I explained. The onblur is triggered first and closes the list without any item being selected.

**Comment by FaridSafi** [comment]
The onBlur is triggered manually inside the _onPress function using .blur()
Touching the rows should not trigger first the onBlur because of the keyboardShouldPersistTaps={true} prop of the ListView. 

This is the example I tested using "react-native": "^0.13.2" and "react-native-google-places-autocomplete": "^1.0.12"
https://gist.github.com/FaridSafi/a6c554328b63743e0255

**Comment by FaridSafi** [comment]
Can you please provide an example then I will look deeply

**Comment by JonnyBGod** [comment]
Sorry I am very busy until sunday. Will get back to this issue on monday with an example.

Meanwhile please check you own example by uncommenting lines 21 and 22. then check if your are getting a result.

**Comment by FaridSafi** [comment]
yes I have the results

**Comment by FaridSafi** [comment]
@JonnyBGod Do you still have issue?

**Comment by FaridSafi** [comment]
I could reproduce the issue by putting the component inside a modal. I suspect a kind of touch conflict between overlapped views. I'm trying to find a solution

**Comment by FaridSafi** [comment]
It seems that keyboardShouldPersistTaps={true} is not effective when there are overlapped scrollable views on react-native 0.13.2 .

I published a new version. The list doesn't close anymore when Blur is triggered. But a second tap is still needed when there is the touch conflict.

**Comment by FaridSafi** [comment]
A quick fix can be to embed the component inside a View instead of ScrollView
