### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by CongCaoDEV** [FaridSafi/react-native-google-places-autocomplete#973]
Warning: TypeError: Cannot read property 'filter' of undefined

**Comment by CongCaoSOF** [comment]
Warning: TypeError: Cannot read property 'filter' of undefined

**Comment by Alfiya-Anjum** [comment]
Hi!! Yes, I tried this one too. I have been having the same error for the past 3 days! I think this might be an issue coz of the update(sdk 53) I don't see a solution for this yet. even after adding predefined Places, it didn't work. its now not suggesting locations... which is crucial for my project!! Let me know if u find a solution for it. =]

**Comment by Zonara-Haroon** [comment]
Yes, I' facing the same issue from yesterday. without predefinedPlaces props field doesn't work it return undefined on filter (package side issue) if i pass predefinedPlaces={[]} than undefined error remove But list not showing on whatever i type. after 2 to 3 words another errror occur which is:

"Error: Exception in HostFunction: Expected argument 7 of method "sendRequest" to be a number, but got undefined"

My code is:
<GooglePlacesAutocomplete
        placeholder={placeholder}
        minLength={3}
        debounce={200}
        fetchDetails={true}
        predefinedPlaces={[]}
        // predefinedPlaces={[
        //   {
        //     description: 'default',
        //     geometry: { location: { lat: 40.714224, lng: -73.961452 } }
        //   },
        //   {
        //     description: 'default2',
        //     geometry: { location: { lat: 40.714224, lng: -73.961452 } }
        //   }
        // ]}
        query={{
          key: routes.googlePlaceKey,
          language: 'en'
        }}
        textInputProps={{
          value: inputValue,
          onChangeText: setInputValue,
          placeholderTextColor: colors?.inputField?.placeholderText,
          fontFamily: FontFamily.regularPro,
          cursorColor: 'black'
        }}
        onPress={(data, details = null) => {
          console.log(data, details);
        }}
        keyboardShouldPersistTap="always"
        enablePoweredByContainer={false}
        onFail={(error) => console.error("Place error:",error)}
        onNotFound={() => console.log("no results")}
        styles={{
          textInputContainer: {...style.input, backgroundColor: bgColor || colors.inputField.bg},
          textInput: style.input,
          listView: {
            zIndex: 9999,
            elevation: 10,
            backgroundColor: 'white',
            borderBottomLeftRadius: width*0.025,
            borderBottomRightRadius: width*0.025,
            top: height*0.005,
            maxHeight: height*0.1,
          },
        }}
      />

if i uncomment predefined obj code than list view show with default values but we want smooth searching process.

How i can fix it. Any solution?

**Comment by HituChhimpa7** [comment]
{/* <GooglePlacesAutocomplete
        textInputProps={{
          onFocus: () => {},
        }}
        placeholder="Search"
        fetchDetails
        predefinedPlaces={[]}
        onPress={(data, details = null) => {
          // 'details' is provided when fetchDetails = true
          console.log(data, details);
        }}
        onFail={error => {
          console.error('GooglePlacesAutocomplete error:', error);
        }}
        query={{
          key: Google key ,
          language: 'en',
        }}
        styles={{
          textInput: {},
          container: {},
        }}
      /> */}


you can solve this error using textInputProps here onFoucs will solve the focus of undefined error
 predefinedPlaces={[]}
 styles={{
          textInput: {},
          container: {},
        }}

and for the styles error you have to pass this also that im facing 
but in my case now after resolving all the cases the list of suggestion from api is not working on getting any success or any error in onFail.

**Comment by sibinmv93** [comment]
I added all supported props with default values and working fine. This is how it looks

```
<GooglePlacesAutocomplete
	placeholder='Search for a Location'
	textInputProps={{ placeholderTextColor: '#000' }}
	styles={{ textInput: { fontSize: 16 } }}
	onPress={(data, details = null) => { console.log(data, details); }}
	query={{
		key: API_KEY,
		language: 'en',
	}}
	
	enablePoweredByContainer={false}
	predefinedPlaces={[]}
	autoFillOnNotFound={false}
	currentLocation={false}
	currentLocationLabel="Current location"
	debounce={0}
	disableScroll={false}
	enableHighAccuracyLocation={true}
	fetchDetails={false}
	filterReverseGeocodingByTypes={[]}
	GooglePlacesDetailsQuery={{}}
	GooglePlacesSearchQuery={{
		rankby: 'distance',
		type: 'restaurant',
	}}
	GoogleReverseGeocodingQuery={{}}
	isRowScrollable={true}
	keyboardShouldPersistTaps="always"
	listHoverColor="#ececec"
	listUnderlayColor="#c8c7cc"
	listViewDisplayed="auto"
	keepResultsAfterBlur={false}
	minLength={0}
	nearbyPlacesAPI="GooglePlacesSearch"
	numberOfLines={1}
	onFail={(e) => { console.warn( 'Google Place Failed : ', e )  }}
	onNotFound={() => { }}
	onTimeout={() => console.warn('google places autocomplete: request timeout')}
	predefinedPlacesAlwaysVisible={false}
	suppressDefaultStyles={false}
	textInputHide={false}
	timeout={20000}
	isNewPlacesAPI={false}
	fields="*"
/>
```

**Comment by HituChhimpa7** [comment]
> I added all supported props with default values and working fine. This is how it looks
> 
> ```
> <GooglePlacesAutocomplete
> 	placeholder='Search for a Location'
> 	textInputProps={{ placeholderTextColor: '#000' }}
> 	styles={{ textInput: { fontSize: 16 } }}
> 	onPress={(data, details = null) => { console.log(data, details); }}
> 	query={{
> 		key: API_KEY,
> 		language: 'en',
> 	}}
> 	
> 	enablePoweredByContainer={false}
> 	predefinedPlaces={[]}
> 	autoFillOnNotFound={false}
> 	currentLocation={false}
> 	currentLocationLabel="Current location"
> 	debounce={0}
> 	disableScroll={false}
> 	enableHighAccuracyLocation={true}
> 	fetchDetails={false}
> 	filterReverseGeocodingByTypes={[]}
> 	GooglePlacesDetailsQuery={{}}
> 	GooglePlacesSearchQuery={{
> 		rankby: 'distance',
> 		type: 'restaurant',
> 	}}
> 	GoogleReverseGeocodingQuery={{}}
> 	isRowScrollable={true}
> 	keyboardShouldPersistTaps="always"
> 	listHoverColor="#ececec"
> 	listUnderlayColor="#c8c7cc"
> 	listViewDisplayed="auto"
> 	keepResultsAfterBlur={false}
> 	minLength={0}
> 	nearbyPlacesAPI="GooglePlacesSearch"
> 	numberOfLines={1}
> 	onFail={(e) => { console.warn( 'Google Place Failed : ', e )  }}
> 	onNotFound={() => { }}
> 	onTimeout={() => console.warn('google places autocomplete: request timeout')}
> 	predefinedPlacesAlwaysVisible={false}
> 	suppressDefaultStyles={false}
> 	textInputHide={false}
> 	timeout={20000}
> 	isNewPlacesAPI={false}
> 	fields="*"
> />
> ```

ITS WORKS FINE

**Comment by asfaarahmed** [comment]
adding this  `predefinedPlaces={[]}` resolved filter crash but dropdown not appearing on search.

```
<GooglePlacesAutocomplete
      ref={addressRef}
      placeholder="Install Address"
      textInputProps={{
        placeholderTextColor: theme.colors.grey3,
        fontSize: 15,
      }}
      styles={{
        textInput: [
            {
              height: Platform.OS === 'ios' ? 35 : 45,
              backgroundColor: 'transparent',
              color: theme.colors.primary,
              fontSize: 15,
              borderWidth: 1,
              borderRadius: 5,
              borderColor: '#CCCCCC',
              paddingLeft: 10,
            },
          ],
          predefinedPlacesDescription: {},
          listView: {fontSize: 15, color: 'red'},
          poweredContainer: {
            display: 'none',
          },
          row: {
            padding: 13,
            height: 38,
            flexDirection: 'row',
            backgroundColor: theme.colors.backgroundColor,
          },
          description: {fontSize: 15, color: theme.colors.primary},
        }}
        onPress={(data, details = null) => {
          setInstallAddress(data.description);
        }}
        query={{
          key: '',
          language: 'en',
          components: 'country:us',
        }}
      />

```

**Comment by zunairaharoon363** [comment]
> > I added all supported props with default values and working fine. This is how it looks
> > ```
> > <GooglePlacesAutocomplete
> > 	placeholder='Search for a Location'
> > 	textInputProps={{ placeholderTextColor: '#000' }}
> > 	styles={{ textInput: { fontSize: 16 } }}
> > 	onPress={(data, details = null) => { console.log(data, details); }}
> > 	query={{
> > 		key: API_KEY,
> > 		language: 'en',
> > 	}}
> > 	
> > 	enablePoweredByContainer={false}
> > 	predefinedPlaces={[]}
> > 	autoFillOnNotFound={false}
> > 	currentLocation={false}
> > 	currentLocationLabel="Current location"
> > 	debounce={0}
> > 	disableScroll={false}
> > 	enableHighAccuracyLocation={true}
> > 	fetchDetails={false}
> > 	filterReverseGeocodingByTypes={[]}
> > 	GooglePlacesDetailsQuery={{}}
> > 	GooglePlacesSearchQuery={{
> > 		rankby: 'distance',
> > 		type: 'restaurant',
> > 	}}
> > 	GoogleReverseGeocodingQuery={{}}
> > 	isRowScrollable={true}
> > 	keyboardShouldPersistTaps="always"
> > 	listHoverColor="#ececec"
> > 	listUnderlayColor="#c8c7cc"
> > 	listViewDisplayed="auto"
> > 	keepResultsAfterBlur={false}
> > 	minLength={0}
> > 	nearbyPlacesAPI="GooglePlacesSearch"
> > 	numberOfLines={1}
> > 	onFail={(e) => { console.warn( 'Google Place Failed : ', e )  }}
> > 	onNotFound={() => { }}
> > 	onTimeout={() => console.warn('google places autocomplete: request timeout')}
> > 	predefinedPlacesAlwaysVisible={false}
> > 	suppressDefaultStyles={false}
> > 	textInputHide={false}
> > 	timeout={20000}
> > 	isNewPlacesAPI={false}
> > 	fields="*"
> > />
> > ```
> 
> IT WORKS FINE

<GooglePlacesAutocomplete
        placeholder={placeholder}
        query={{
          key: routes.googlePlaceKey,
          language: 'en'
        }}
        textInputProps={{
          value: inputValue,
          onChangeText: text => setInputValue(text),
          placeholderTextColor: colors?.inputField?.placeholderText,
          fontFamily: FontFamily.regularPro,
          cursorColor: 'black'
        }}
        onPress={(data, details = null) => { console.log(data, details)}}
        styles={{
          textInput: {...style.input, backgroundColor: bgColor || colors.inputField.bg},
          listView: {
            elevation: 10,
            backgroundColor: 'white',
            borderBottomLeftRadius: width*0.025,
            borderBottomRightRadius: width*0.025,
            top: height*0.005,
          },
        }}
        onFail={(error) => console.error("Place error:",error)}
        onNotFound={() => console.log("no results")}
        enablePoweredByContainer={false}
        predefinedPlaces={[]}
        autoFillOnNotFound={false}
        currentLocation={false}
        currentLocationLabel="Current location"
        debounce={10}
        disableScroll={false}
        enableHighAccuracyLocation={true}
        fetchDetails={true}       
        isRowScrollable={true}
        keyboardShouldPersistTaps="always"
        listViewDisplayed="auto"
        minLength={2}
        nearbyPlacesAPI="GooglePlacesSearch"
	      numberOfLines={1}
        onTimeout={() => console.warn('google places autocomplete: request timeout')}
        predefinedPlacesAlwaysVisible={false}
        suppressDefaultStyles={false}
        timeout={20000}
      />

Thank you with the help of your suggestion List view is enable to display.. but now onPress isn't working. Whatever i select from list onPress log not work even nothing happened in input field.

**Comment by featlast** [comment]
Greetings 🤗, at the moment for Android it does not allow onPress to be performed on any direction suggestion, only on iOS it works correctly, definitely to move forward I will have to go back to react native 0.77, it is still unstable in react native 0.79.2

**Comment by fluxc** [comment]
This what is working for me on both IOS and Android
"react-native": "0.79.2",     "expo": "^53.0.9",     "react-native-google-places-autocomplete": "^2.5.6",
<GooglePlacesAutocomplete
								ref={inputRef}
								query={{
									key: process.env.EXPO_PUBLIC_GOOGLE_API_KEY,
									language: i18n.language,
								}}
								renderLeftButton={() => (
									<InputIcon>
										<Feather name='search' size={22} color={colors.text.secondary} />
									</InputIcon>
								)}
								textInputProps={{
									placeholderTextColor: colors.text.secondary,
								}}
								styles={placesAutoComplete()}
								minLength={2}
								enablePoweredByContainer={false}
								fetchDetails={true}
								placeholder={t('Enter address')}
								debounce={300}
								predefinedPlaces={[]}
								filterReverseGeocodingByTypes={[]}
								predefinedPlacesAlwaysVisible={false}
								timeout={20000}
								isRowScrollable={true}
								keyboardShouldPersistTaps='always'
								keepResultsAfterBlur={false}
								onPress={(data, details = null) => {
									if (data.description) {
										const selectedAddress = {
											latitude: details?.geometry.location.lat!,
											longitude: details?.geometry.location.lng!,
											selectedStreet: data.description,
											selectedCountry:
												details?.address_components[details?.address_components.length - 1]
													.long_name || '',
										};
										submitSearch(selectedAddress);
									}
								}}
							/>

**Comment by rodnnnney** [comment]
I no longer get the filter undef error but now I am getting a `crypto.getRandomValues()` not supported error. Has anyone else random into this after applying the temporary fixes listed above? I implemented @zunairaharoon363 's solution.

![Image](https://github.com/user-attachments/assets/b7c18938-e74f-43ea-9325-f1f09b0bbb59)

**Comment by dhairyasenjaliya** [comment]
for those who are still facing this just add `predefinedPlaces={[]}` but also we need to set `minLength={1}` in-order to fetch list as well

**Comment by MackKaputo** [comment]
@rodnnnney  Also getting the `crypto.getRandomValues()` not supported error after applying predefinedPlaces={[]}

  "expo": "^53.0.9",
    "react-native": "0.79.2"

Any solution to this?

**Comment by Pupsentiy** [comment]
> [@rodnnnney](https://github.com/rodnnnney) Also getting the `crypto.getRandomValues()` not supported error after applying predefinedPlaces={[]}
> 
> "expo": "^53.0.9", "react-native": "0.79.2"
> 
> Any solution to this?

install "react-native-get-random-values" and
Add the 'react-native-get-random-values' import to the main index.js/ts app;

**Comment by patrickomeara** [comment]
@IamDixit 

Try adding `textInputProps` to your props

```tsx
    <GooglePlacesAutocomplete
        //
       predefinedPlaces={[]}
       textInputProps={{}}
    />
```

I think we need to start looking at alternatives for this packages. ❤

**Comment by AlexKenny6** [comment]
I'm on:

"react-native": "0.79.2",
 "expo": "^53.0.0",


In order for this to work for me, I had to add all of the supported props with default values that I wasn't already using 
shown in a previous comment, had to install react-native-get-random-values and add its import to my index.js file.

What my code looks like now:

```
<GooglePlacesAutocomplete
                placeholder={"Search location..."}
                minLength={2}
                query={{
                    key: googlePlacesKey,
                    language: "en",
                }}
                fetchDetails={true}
                onPress={(data, details) => {
                    setLocation(data);
                    setLocationDetails(details);
                }}
                textInputProps={{
                    placeholderTextColor: "white",
                    color: "white",
                }}
                styles={{
                    separator: null,
                    textInputContainer: {
                        backgroundColor: "dodgerBlue",
                        width: "100%",
                    },
                }}
                // Default props
                enablePoweredByContainer={false}
                predefinedPlaces={[]}
                autoFillOnNotFound={false}
                currentLocation={false}
                currentLocationLabel="Current location"
                debounce={0}
                disableScroll={false}
                enableHighAccuracyLocation={true}
                filterReverseGeocodingByTypes={[]}
                GooglePlacesDetailsQuery={{}}
                GooglePlacesSearchQuery={{
                    rankby: "distance",
                    type: "restaurant",
                }}
                GoogleReverseGeocodingQuery={{}}
                isRowScrollable={true}
                keyboardShouldPersistTaps="always"
                listHoverColor="#ececec"
                listUnderlayColor="#c8c7cc"
                listViewDisplayed="auto"
                keepResultsAfterBlur={false}
                nearbyPlacesAPI="GooglePlacesSearch"
                numberOfLines={1}
                onFail={(e) => {
                    console.warn("Google Place Failed : ", e);
                }}
                onNotFound={() => {}}
                onTimeout={() => console.warn("google places autocomplete: request timeout")}
                predefinedPlacesAlwaysVisible={false}
                suppressDefaultStyles={false}
                textInputHide={false}
                timeout={20000}
                isNewPlacesAPI={false}
                fields="*"
            />
```

**Comment by AbdullahBinAmir** [comment]
I added a custom component in my project because GooglePlacesAutoComplete with the above solution was not giving me coordinates in the response :

`// Custom Places API service
const PlacesService = {
  searchPlaces: async (query: string) => {
    try {
      const response = await fetch(
        `https://maps.googleapis.com/maps/api/place/autocomplete/json?input=${encodeURIComponent(
          query
        )}&key=${GOOGLE_MAPS_API_KEY}&sessiontoken=${Math.random().toString(36).substring(2, 15)}`
      )
      const data = await response.json()
      return data.predictions || []
    } catch (error) {
      console.error("Error searching places:", error)
      return []
    }
  },
  
  getPlaceDetails: async (placeId: string) => {
    try {
      const response = await fetch(
        `https://maps.googleapis.com/maps/api/place/details/json?place_id=${placeId}&fields=geometry,formatted_address&key=${GOOGLE_MAPS_API_KEY}`
      )
      const data = await response.json()
      return data.result || null
    } catch (error) {
      console.error("Error getting place details:", error)
      return null
    }
  },
  
  getAddressFromCoordinates: async (latitude: number, longitude: number) => {
    try {
      const response = await fetch(
        `https://maps.googleapis.com/maps/api/geocode/json?latlng=${latitude},${longitude}&key=${GOOGLE_MAPS_API_KEY}`
      )
      const data = await response.json()
      if (data.results && data.results.length > 0) {
        return data.results[0].formatted_address
      }
      return ""
    } catch (error) {
      console.error("Error getting address:", error)
      return ""
    }
  }
}

// Custom Autocomplete component
const PlacesAutocomplete = ({ 
  placeholder, 
  onLocationSelect, 
  onClose,
  showCurrentLocation = false,
  currentLocationLabel = "Use my current location"
}:any) => {
  const { colors } = useTheme()
  const [query, setQuery] = useState("")
  const [predictions, setPredictions] = useState([])
  const [loading, setLoading] = useState(false)
  
  useEffect(() => {
    const searchTimeout = setTimeout(() => {
      if (query.length > 2) {
        searchPlaces(query)
      } else {
        setPredictions([])
      }
    }, 300)
    
    return () => clearTimeout(searchTimeout)
  }, [query])
  
  const searchPlaces = async (text: string) => {
    setLoading(true)
    const results = await PlacesService.searchPlaces(text)
    setPredictions(results)
    setLoading(false)
  }
  
  const handleSelectPlace = async (placeId: string, description: string) => {
    const details = await PlacesService.getPlaceDetails(placeId)
    console.log(details)
    if (details && details.geometry) {
      onLocationSelect({
        latitude: details.geometry.location.lat,
        longitude: details.geometry.location.lng,
        address: details.formatted_address || description
      })
    }
  }
  
  const handleSelectCurrentLocation = async () => {
    try {
      const { status } = await Location.requestForegroundPermissionsAsync()
      if (status !== "granted") {
        Alert.alert("Permission denied", "Location permission is required")
        return
      }
      
      const location = await Location.getCurrentPositionAsync({})
      const { latitude, longitude } = location.coords
      const address = await PlacesService.getAddressFromCoordinates(latitude, longitude)
      
      onLocationSelect({
        latitude,
        longitude,
        address
      })
    } catch (error) {
      console.error("Error getting current location:", error)
      Alert.alert("Error", "Failed to get current location")
    }
  }
  
  return (
    <View style={{ flex: 1, backgroundColor: colors.background }}>
      <View style={styles.autocompleteHeader}>
        <TouchableOpacity onPress={onClose}>
          <Ionicons name="arrow-back" size={24} color={colors.text} />
        </TouchableOpacity>
        <Text style={[styles.autocompleteTitle, { color: colors.text }]}>{placeholder}</Text>
        <View style={{ width: 24 }} />
      </View>
      
      <TextInput
        style={[styles.searchInput, { 
          backgroundColor: colors.card, 
          color: colors.text,
          borderColor: colors.border
        }]}
        placeholder={placeholder}
        placeholderTextColor={colors.lightGray}
        value={query}
        onChangeText={setQuery}
        autoFocus
      />
      
      {loading && (
        <View style={styles.loadingContainer}>
          <ActivityIndicator color={colors.primary} />
        </View>
      )}
      
      <FlatList
        data={predictions}
        keyExtractor={(item:any) => item.place_id}
        ListHeaderComponent={
          showCurrentLocation ? (
            <TouchableOpacity 
              style={[styles.currentLocationItem, { borderBottomColor: colors.border }]} 
              onPress={handleSelectCurrentLocation}
            >
              <Ionicons name="locate" size={24} color={colors.primary} style={styles.placeIcon} />
              <Text style={[styles.currentLocationText, { color: colors.text }]}>{currentLocationLabel}</Text>
            </TouchableOpacity>
          ) : null
        }
        renderItem={({ item }:any) => (
          <TouchableOpacity 
            style={[styles.predictionItem, { borderBottomColor: colors.border }]} 
            onPress={() => handleSelectPlace(item.place_id, item.description)}
          >
            <Ionicons name="location-outline" size={24} color={colors.text} style={styles.placeIcon} />
            <View>
              <Text style={[styles.predictionText, { color: colors.text }]} numberOfLines={1}>
                {item.structured_formatting?.main_text || item.description.split(',')[0]}
              </Text>
              <Text style={[styles.predictionSecondaryText, { color: colors.lightGray }]} numberOfLines={1}>
                {item.structured_formatting?.secondary_text || item.description.split(',').slice(1).join(',')}
              </Text>
            </View>
          </TouchableOpacity>
        )}
      />
    </View>
  )
}`

**Comment by patrickomeara** [comment]
Hi @AbdullahBinAmir try wrapping your code in 

````
```tsx
 // code here
```
````

github will format it for you.

**Comment by phatlaunchdeck** [comment]
This must be due to React 19's removal of default props

**Comment by patrickomeara** [comment]
Has anyone found a maintained alternative to this package? Preferably written in typescript?

**Comment by devartwa** [comment]
> Has anyone found a maintained alternative to this package? Preferably written in typescript?

I wish, I'm having a lot of issues after my last react native upgrade.

**Comment by dmitryusikriseapps** [comment]
The only way to get it working for both iOS and Android platforms is to copy default props from the package and pass them manually to the places input:
```ts
const defaultProps: GooglePlacesAutocompleteProps = {
  autoFillOnNotFound: false,
  currentLocation: false,
  currentLocationLabel: 'Current location',
  debounce: 0,
  disableScroll: false,
  enableHighAccuracyLocation: true,
  enablePoweredByContainer: true,
  fetchDetails: false,
  fields: '*',
  filterReverseGeocodingByTypes: [],
  GooglePlacesDetailsQuery: {},
  GooglePlacesSearchQuery: {
    rankby: 'distance',
    type: 'restaurant',
  },
  GoogleReverseGeocodingQuery: {},
  isNewPlacesAPI: false,
  isRowScrollable: true,
  keepResultsAfterBlur: false,
  keyboardShouldPersistTaps: 'always',
  listHoverColor: '#ececec',
  listUnderlayColor: '#c8c7cc',
  listViewDisplayed: 'auto',
  minLength: 0,
  nearbyPlacesAPI: 'GooglePlacesSearch',
  numberOfLines: 1,
  onFail: () => {},
  onNotFound: () => {},
  onPress: () => {},
  // eslint-disable-next-line no-console
  onTimeout: () => console.warn('google places autocomplete: request timeout'),
  placeholder: '',
  predefinedPlaces: [],
  predefinedPlacesAlwaysVisible: false,
  query: {
    key: 'missing api key',
    language: 'en',
    type: 'geocode',
  },
  styles: {},
  suppressDefaultStyles: false,
  textInputHide: false,
  textInputProps: {},
  timeout: 20000,
};

<GooglePlacesAutocomplete
        {...defaultProps}
        fetchDetails
        filterReverseGeocodingByTypes={['establishment', 'street_address']}
        GooglePlacesDetailsQuery={detailsQuery}
        onPress={handlePlaceSelect}
        placeholder={t('search')}
        query={query}
        ref={input}
        styles={autocompleteStyles}
      />
```

**Comment by dylan-bakr** [comment]
@patrickomeara 
> Has anyone found a maintained alternative to this package? Preferably written in typescript?
[`expo-google-places`](https://github.com/devpgcs/expo-google-places) is still under development but i was able to get the search box implemented on mobile -- still lacks web support which has been my headache even with all the workarounds for this package

**Comment by hamza-saqib** [comment]
@CongCaoSOF @Zonara-Haroon @MackKaputo 

I solved it, in my Expo SDK 53.

Error was: `Cannot read property 'filter' of undefined`

I added these 3 lines:
```
predefinedPlaces={[]}
textInputProps={{}}
minLength={2}
```

the you willget another error  that @MackKaputo has, then install package : 
```
npm i react-native-get-random-values
```
the add line on top of your root file:
```
`import 'react-native-get-random-values';
```

**Comment by dylan-bakr** [comment]
@hamza-saqib have you been able to achieve web support?

**Comment by amitpdev** [comment]
> Has anyone found a maintained alternative to this package? Preferably written in typescript?

[Yep](https://github.com/amitpdev/react-native-google-places-textinput)

**Comment by harwinderindiit** [comment]
@amitpdev 
Create a new issues and mention this alternate their. I have tried searching it in the google and its not indexed yet

**Comment by Shivamlab** [comment]
> predefinedPlaces={[]}
> keyboardShouldPersistTaps="always"
> minLength={3}
> timeout={20000}
> I was facing some issues after upgrading my react-native version from 0.75.3 to 0.79.1, for some reason I had to add these props above.
> 
> It is working perfectly now, I'm just posting because it can help someone. 😄

Thanks , it worked .

**Comment by HamzaJameel01** [comment]
I faced all the above errors, but I was able to fix them. Now everything is working fine on both Android and iOS. Let me explain how I resolved them:

1-Random Values Error:
I installed the library react-native-get-random-values and imported it at the top of the App.tsx file. Then, I rebuilt the app.
2- Error: Cannot read property 'onFocus' of undefined:
To fix this, I applied:
textInputProps={{
  onFocus: () => {},
}}
3-Error: Cannot read property 'container' of undefined:
styles={{
  container: {
    flex: 0, // or use flex: 1 if you want it to fill the space
  },
  textInputContainer: {
    width: '100%',
  },
  textInput: {
    height: 44,
    color: '#5d5d5d',
    fontSize: 16,
  },
}}
And here is how my GooglePlacesAutocomplete component looks now:
<GooglePlacesAutocomplete
  placeholder="Search"
  onPress={(data, details = null) => {
    console.log(data, details);
  }}
  query={{
    key:'Your_Api_Key',
    language: 'en',
  }}
  predefinedPlaces={[] as any}
  fetchDetails={true}
  debounce={200}
  enablePoweredByContainer={false}
  keyboardShouldPersistTaps="always"
  minLength={3}
  timeout={20000}
  styles={{
    container: {
      flex: 0, // or flex: 1 if you want it to fill the space
    },
    textInputContainer: {
      width: '100%',
    },
    textInput: {
      height: 44,
      color: '#5d5d5d',
      fontSize: 16,
      borderWidth: 1,
    },
  }}
  textInputProps={{
    onFocus: () => {
      console.log('Input focused');
    },
  }}
/>
